### ISSUE TITLE
Separate partials in a different directory from pages templates

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#12]
At the moment the partials are inside of the page-templates folder, make sure to move the partials into the root directory of the level and update the code that load other partials.

**Comment by joseph-jalbert** [comment]
I will take care of this, just a heads up, can't assign it to myself

**Comment by mitogh** [comment]
let me add you into the project @joseph-jalbert

**Comment by mitogh** [comment]
Let me know your progress on this @joseph-jalbert to see where I can continue working, also please make sure to create a branch to work on this feature.

Thanks.

**Comment by joseph-jalbert** [comment]
will do. to clarify, they should be in the page-templates folder, root of theme folder itself?

**Comment by mitogh** [comment]
Similar to this one: https://github.com/moxienyc/Caleres/tree/master/wp-content/themes/caleres

If you see views, but in this case is called partials. @joseph-jalbert

**Comment by mitogh** [comment]
Thanks for your help @joseph-jalbert, excellent job. I'm closing this one.
