### ISSUE TITLE
Create Logo for "Lean" or "LEAN"

### ISSUE THREAD

**Issue by jeffreynolte** [moxie-leean/Leean#14]
@MarianoMiguel If you can pickup this task when you get a moment that would be great.

**Comment by MarianoMiguel** [comment]
@jeffreynolte Been experimenting a bit with this. Not exactly my strongest side but take a look:

![logos](https://cloud.githubusercontent.com/assets/880223/10580732/48135826-7655-11e5-884c-e536e1975a79.jpg)

**Comment by jeffreynolte** [comment]
@MarianoMiguel - Not bad as a start but I feel it needs some work. A couple notes
- Your kerning / letter spacing is off on the logo
- Why not use the same weight as the letters for the icon?
- The last one is my favorite as it is most symmetrical
- Try incorporating some of the elements we are using into this like WP, or Theme development, or node, etc.
- Maybe illustrate the stack in an icon with the different technologies (JS, PHP, etc)
- Try integrating the tagline into the logo
- Explore some color variations.
- This can also be fun, funny or kitch try playing with some different icons to illustrate this.
- I would share with the team to get additional input.

No hurry but wanted to get my comments down.

**Comment by orcunilbeyli** [comment]
We covered some road with Jeffrey on this. What do you think about it guys?

![lean logo](https://cloud.githubusercontent.com/assets/1042651/11121125/cd405336-895c-11e5-9030-c3f4f42a6789.png)

**Comment by jeffreynolte** [comment]
@mitogh - as discussed we moved to the new leean name. I am thinking it may be even better with 3 e. "Leeean" as it is more exaggerated. Looking for some feedback from all here. 

Nice work @nucro

**Comment by orcunilbeyli** [comment]
I think "**Leeean**" sounds like "Lean back and let the Leeean do the work while you doing something else." 
Because of that **Leean** is better, in my opinion. @jeffreynolte

**Comment by jeffreynolte** [comment]
Closing this one out @nucro. Nice work.
