### ISSUE TITLE
Unitless Line-Heights

### ISSUE THREAD

**Issue by MarianoMiguel** [moxie-leean/Leean#35]
Hey guys, great work here! Just wanted to throw my 2 cents in. I was taking a look at https://github.com/moxienyc/Moxie-Lean/blob/master/assets/sass/layouts/_typography.scss and I noticed you're using em's for setting line-heights. 

There's an intentional semantic difference in the CSS spec between 1.5 and 1.5em/150%. A unitless value is passed to the child element and its line height is calculated using the child's font size, whereas a percentage or em value will cause a line height to be calculated for the parent, and then that calculated value is passed to the child.

Quoting [CSS-Tricks](https://css-tricks.com/almanac/properties/l/line-height/):

"The recommended method for defining line height is using a number value, referred to as a "unitless" line height. A number value can be any number, including a decimal-based number, as is used in the first code example on this page.

Unitless line heights are recommended due to the fact that child elements will inherit the raw number value, rather than the computed value. With this, child elements can compute their line heights based on their computed font size, rather than inheriting an arbitrary value from a parent that is more likely to need overriding."

@mitogh @nacho87

**Comment by mitogh** [comment]
Thank you @MarianoMiguel I will take a look in your suggestion.

Really appreciate it!
