### ISSUE TITLE
No Browser Sync?

### ISSUE THREAD

**Issue by digisavvy** [moxie-leean/Leean#38]
Hey there,
Just curious if there were plans to bake-in browser sync or not? Curious why it's not included. =)

**Comment by mitogh** [comment]
Hey @digisavvy!

Yes absolutely `browser sync` is one of the coolest thing outside, we removed from original theme in order to create a gulpfile from scratch. Hopefully we can add it in the next days or weeks if possible. :+1:

**Comment by digisavvy** [comment]
If I find some time and it hasn't been added, I'm happy to do so myself. =) We'll see who gets to it first!

**Comment by mitogh** [comment]
Sounds good I will create an issue and closing this one. 

Thank you @digisavvy
