### ISSUE TITLE
Add basic styles to use Moxie Lean.

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#41]
I guess to have a set of base styles can be a good idea some like: Twenty Fifteen or kind of to showcase much better initial scaffold.

**Comment by orcunilbeyli** [comment]
Yes. Great idea. I can start working on them after finalizing the disturbution page of the theme.

**Comment by mitogh** [comment]
Where do we stand on this task @nucro ?

**Comment by orcunilbeyli** [comment]
Did some sketches and samples. Started today. Will let you know when first sample is ready.

 Regards.

**Comment by orcunilbeyli** [comment]
I think basic theme seems okay for now. I'll make some makeups and latest fixes on design of Leean if backend has no bugs for now. Waiting for your feedbacks Cris. @mitogh

**Comment by mitogh** [comment]
Ok let me know once we are ready to review.

**Comment by mitogh** [comment]
Thank you @nucro for your job on this, I'm closing this one since the changes has been integrated on development.
