### ISSUE TITLE
Load jQuery using a CDN from Google

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#51]

**Comment by orcunilbeyli** [comment]
On it.

**Comment by mitogh** [comment]
Some other notes @nucro 
- For production we use CDN from Google
- For development we use the one from bower.

**Comment by mitogh** [comment]
Let me know once this is completed in order to be reviewed

**Comment by orcunilbeyli** [comment]
Okay @mitogh I am on @jrrrsmith 's feedbacks for now. I'll take care of it once this finished and will let you know asap.

**Comment by mitogh** [comment]
Moved into the repo, since assets are not part anymore from this repo.
