### ISSUE TITLE
Add bootstrap file

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#53]
This file will serve as the entry point to load different helpers to be used in the theme.

**Comment by mitogh** [comment]
I think for this should be better if we have an App class that holds all configurations for the theme like: 

```
App
```

Same way as Laravel does.

**Comment by adamf321** [comment]
Yes, we could do that.

In general I think we could tidy it all up a bit. I was just looking at an issue with Nacho in Amtrak - it's very complicated how we're loading so many different config files and setting up constants. I think this could be simplified.

**Comment by mitogh** [comment]
Yes I agree we can simplify things however I would say we need a place for storage all constants like field names in order to be reused in other places

**Comment by adamf321** [comment]
Yes. I was thinking we could even consider a more modular approach to the structure. This would involve actually splitting things by function rather than file type EG:

```
modules/
  contact-form/
     helper.php
    constants.php
    _styles.sass
    script.js
   ...
```

**Comment by mitogh** [comment]
OK i think that could be a way to do so, but I'm wondering what type of modules? and this can be confuse with the node modules directory as well. I was thinking to having a general class where we can extend or inherent that class in order to set up those type of things

**Comment by adamf321** [comment]
I mean grouping code by functionality - eg a module is all code which affects the woocommerce single product page. For me this makes it easier to find all related code. I can draw up an example if it's not clear...

I'm not sure exactly how you're thinking of using the general class.
