### ISSUE TITLE
Content hover should have a transition

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#60]
Take a look at the other elements like the button for example of the comment, those hover states has a transition before change of color, in my personal opinion this will make things more smoothly. 

Let me know if you have any question about this.

Thanks.

**Comment by orcunilbeyli** [comment]
We can use transition for buttons but imho, anchor links should not have transition. What do you think? @mitogh

**Comment by mitogh** [comment]
Transitions between colours, take a look at the original link style of the Leen theme there was a transition on color change of each link. @nucro

**Comment by orcunilbeyli** [comment]
Yeah I know. I removed them because it didn't look well on colors. I can put them back if you want. I am just explaining my humble opinion. I am talking about anchor link transitions btw.

**Comment by mitogh** [comment]
Ok I think this is what we are going to do.
1. Create 1 extra class something like: `content--transitions` or anything you feel is better.
2. All links inside of this container are going to have transitions.
3. We add or remove this class on the content container in order to have both behaviours and decide on future any one.

Let me know if that makes sense to you.

**Comment by orcunilbeyli** [comment]
Okay. On it. Thanks.

**Comment by jrrrsmith** [comment]
@nucro looks good, and yes please reference the issue in your commit so we can find the changes faster, that would be a big help.  Good job.  Closing.
