### ISSUE TITLE
Pagination it's not aligned correctly

### ISSUE THREAD

**Issue by mitogh** [moxie-leean/Leean#61]
Please refer to the next capture:

![screen shot 2015-12-14 at 07 30 58](https://cloud.githubusercontent.com/assets/3921289/11782119/ad6d412c-a234-11e5-90dd-6a5ac20d5d85.png)

The navigation items should be split on left and right for example: 

```
prev                       next
```

Let me know if that makes sense to you or if you have any other extra question about this.

Thank you.

**Comment by orcunilbeyli** [comment]
@jrrrsmith I do the fixes. Please review and let me know if there are still issues. I also assigned you to other issues too.

**Comment by jrrrsmith** [comment]
@nucro looks good to me thanks, I'll close this one

cc/ @mitogh

**Comment by mitogh** [comment]
Hey @nucro as a suggestion please include the issue number on the commit in order to keep track of the changes introduced on each commit.

Thanks.

**Comment by orcunilbeyli** [comment]
Okay guys. Thanks for feedback. Will fix asap. @mitogh @jrrrsmith
